version: '3.8'

services:
  books:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8009:8000
    env_file:
      - ./app/.env.dev
    depends_on:
      - books-db

  books-db:
    image: postgres:14-alpine
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    environment:
    - POSTGRES_USER=books
    - POSTGRES_PASSWORD=books
    - POSTGRES_DB=books_dev
    ports:
      - 5432:5432

volumes:
  postgres_data: